### ISSUE TITLE
Possible to download an entire subreddit at once?

### ISSUE THREAD

**Issue by lightninghydra24** [nilfoer/gwaripper#10]
Thanks for this project! It looks great :)

Is it possible to download every post from a subreddit? I was thinking something like `subreddit 999999999 GoneWildAudioGay` or something might work, but am not too sure if you'd have to use something like pushshift for that..

**Comment by nilfoer** [comment]
Unfortunately it's not possible using the regular reddit API and currently I don't want to take on another dependency just for this. Sorry!

Maybe using different search terms + sorting orders is enough.

**Comment by lightninghydra24** [comment]
No worries! :) I think perhaps the reddit_it or URL option would work. Thanks for making this available to us
