### ISSUE TITLE
Can not create the config file

### ISSUE THREAD

**Issue by gigatag** [nilfoer/gwaripper#13]
First of all a great idea with the gonne wild scraper. Thx

I wanted to use this tool also gladly only I do not get it to run on my pc.
I have installed python 3.11 and 3.09 on windows 11, and I have also the requirements.txt installed.
When I want to start it I do not get the config file written to the root folder.
How could i fix this problem, do you have any idea?
Thanks for any help  ♥

> `PS C:\Users\***\Downloads\GWARipper-0.6.8> python gwaripper-runner.py
No arguments passed! Call this script from the command line with -h to show available commands.
Simulating command line input!!

Type in command line args:

root_path not set in gwaripper_config.ini, use command config -p "C:\absolute\path" to specify where the files will be downloaded to
PS C:\Users\***\Downloads\GWARipper-0.6.8> python gwaripper-runner.py config -p
usage: gwaripper-runner.py config [-h] [-p PATH] [-bf FREQUENCY] [-bn N-BACKUPS] [-tf TAG [TAG ...]]
                                  [-tco TAGCOMBO [TAGCOMBO ...]] [-smr {0,1}] [-rci client_id] [-rcs client_secret]
                                  [-ici imgur_client_id] [--only-one-mirror ZERO_OR_ONE] [--host-priority]
gwaripper-runner.py config: error: argument -p/--path: expected one argument
PS C:\Users\***\Downloads\GWARipper-0.6.8>`

**Comment by nilfoer** [comment]
You're missing the path argument after `config -p`: `python gwaripper-runner.py config -p "C:\Users\username\your\desired\path"`
