### ISSUE TITLE
HTTP 302 / ERR_CONNECTION_REFUSED when connecting to WebGUI from other computer in LAN

### ISSUE THREAD

**Issue by porotect** [nilfoer/gwaripper#17]
When I connect to the WebGUI from another computer in my LAN, the site doesn't load and I get an ERR_CONNECTION_REFUSED error. I tested this with Firefox and the Brave browser.

I get this message from the terminal that launched the WebGUI, whenever this happens:  "GET / HTTP/1.1" 302 -

I run GWARipper through this build: GWARipper-v0.8.0_single-folder_lin-x64

**Comment by nilfoer** [comment]
Did you run the WebGUI with `gwaripper.exe webgui open`?

**Comment by porotect** [comment]
I was missing the "open" part. Thanks now it works for me.
