### ISSUE TITLE
can't get it to work on linux anymore.

### ISSUE THREAD

**Issue by cdothour** [nilfoer/gwaripper#4]
Used to have no problem using gwaripper on linux. However, for the past 6 months or so I have not been able to use it for some reason. 

It's giving me "Uncaught exceptions" error:
image link here: https://files.catbox.moe/zqgml1.png

install method via: > python -m pip install -r requirements.txt
and running with the following command: python gwaripper-runner.py

**Comment by nilfoer** [comment]
Hey, you are using python version `3.10`, which was not supported by gwaripper's newest `flask` version. I updated `flask` in the `requirements.txt` in the newest commit [502fd36](https://github.com/nilfoer/gwaripper/commit/502fd364f55f3ee7dd04ec68e426b1156c7cb6e2) to support python >=3.10.

Hope this fixes it for you!

**Comment by cdothour** [comment]
Thank you so much nilfoer! It works now.
I'm running arch so the python version is always updated to the latest. 
Really appreciate the new commit!
