### ISSUE TITLE
Issues displaying certain audios

### ISSUE THREAD

**Issue by Inexpress** [nilfoer/gwaripper#6]
I've had an issue where certain audios, despite downloading fine (metadata and audio files downloaded, audio is not corrupted), are not recognised and cannot be embedded in the web player ("Local file couldn't be found" error).

Two audios with which I reproduced the issue on a clean install:
aHR0cHM6Ly93d3cucmVkZGl0LmNvbS9yL2dvbmV3aWxkYXVkaW8vY29tbWVudHMvb3lxNzJ0L2Y0bV9mcm9tX2Rpc29iZWRpZW50X3RlZW5fdG9fc3VibWlzc2l2ZV9mdWNrLw==
aHR0cHM6Ly9yZWRkaXQuY29tL3IvZ29uZXdpbGRhdWRpby9jb21tZW50cy9wcWJ3M3kvZjRtX2NsYXNzbWF0ZV9naXZlc195b3Vfc2VydmljZV9jaGlsZGhvb2Qv

I might well be doing something wrong here, in which case I apologise. Thank you for the useful tool.

**Comment by nilfoer** [comment]
Should be fixed in [d6349](https://github.com/nilfoer/gwaripper/commit/d63493f4b4d6b054c63edd2f8fb4fbc6168c023d)
